before:
  hooks:
    - go mod download
builds:
  -
    env:
      - CGO_ENABLED=0

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - 6
      - 7

    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'